name: "Mantegna2019"

dataset: 
  # - name: BrainInvaders2015a
  #   from: deeb.datasets
  #   parameters: 
  #     subjects: [5,30]
  #     interval: [-0.1, 0.9]

  # - name: Mantegna2019
  #   from: deeb.datasets
  #   parameters: 
  #     subjects: [5,10]
  #     interval: [-0.1, 0.9]

  # - name: Lee2019
  #   from: deeb.datasets
  #   parameters: 
  #     subjects: 10
  #     interval: [-0.1, 0.9]

  - name: ERPCOREN400
    from: deeb.datasets
  #   parameters: 
  #     subjects: 10
  # #     #interval: [-0.1, 0.9]

  # # - name: COGBCIFLANKER
  # #   from: deeb.datasets
  # #   parameters: 
  #     subjects: 10
      #interval: [-0.1, 0.9]

pipelines:

  # "AR+SVM": 
  #   - name: AutoRegressive
  #     from: deeb.pipelines
  #     parameters: 
  #       order: 8
        
  #   # - name: PowerSpectralDensity
  #   #   from: deeb.pipelines
        
  #   - name: SVC
  #     from: sklearn.svm
  #     parameters: 
  #       kernel: 'rbf'
  #       class_weight: "balanced"
  #       probability: True

 
  "PSD+LG": 
  # - name: AutoRegressive
  #   from: deeb.pipelines
  #   parameters: 
  #     order: 6
    
  - name: PowerSpectralDensity
    from: deeb.pipelines
      
  - name: LogisticRegression
    from: sklearn.linear_model
    parameters: 
        #kernel: 'rbf'
        class_weight: "balanced"
        #probability: True

  # "AR+PSD+RF": 
  # - name: AutoRegressive
  #   from: deeb.pipelines
  #   parameters: 
  #     order: 6
    
  # - name: PowerSpectralDensity
  #   from: deeb.pipelines
      
  # - name: RandomForestClassifier
  #   from: sklearn.ensemble
  #   parameters: 
  #       #kernel: 'rbf'
  #       class_weight: "balanced"
  #       #probability: True

  "AR+PSD+LDA": 
    - name: AutoRegressive
      from: deeb.pipelines
      parameters: 
        order: 6
      
    - name: PowerSpectralDensity
      from: deeb.pipelines
        
    - name: LinearDiscriminantAnalysis
      from: sklearn.discriminant_analysis 
      parameters: 
        solver: 'lsqr'
        #class_weight: "balanced"
        shrinkage: 'auto'

  # "SNN": 
  #   - name : Siamese
  #     from: deeb.pipelines
  #     parameters: 
  #       EPOCHS: 5
  #       batch_size: 256
  #       verbose: 1
  #       workers: 1

  # "AR+PSD+KNN": 
  #   - name: AutoRegressive
  #     from: deeb.pipelines
  #     parameters: 
  #       order: 6
      
  #   - name: PowerSpectralDensity
  #     from: deeb.pipelines
        
  #   - name: KNeighborsClassifier
  #     from: sklearn.neighbors
  #     # parameters: 
  #     #   #kernel: 'rbf'
  #     #   class_weight: "balanced"
  #     #   #probability: True

  "AR+PSD+GNB": 
    - name: AutoRegressive
      from: deeb.pipelines
      parameters: 
        order: 6
      
    - name: PowerSpectralDensity
      from: deeb.pipelines
      
    - name: GaussianNB
      from: sklearn.naive_bayes




