name: "UserDataset"

dataset: 
  - name: COGBCIFLANKER
    from: deeb.datasets
    parameters: 
      subjects: 10
      interval: [-0.1, 0.9]
      rejection_threshold: 200


pipelines:

  "AR+PSD+SVM": 
    - name: AutoRegressive
      from: deeb.pipelines
      parameters: 
        order: 6
        
    - name: PowerSpectralDensity
      from: deeb.pipelines
        
    - name: SVC
      from: sklearn.svm
      parameters: 
        kernel: 'rbf'
        class_weight: "balanced"
        probability: True

  "Siamese": 
    - name : Siamese
      from: deeb.pipelines
      parameters: 
        EPOCHS: 10
        batch_size: 256
        verbose: 1
        workers: 1

  
  "AR+PSD+RF": 
  - name: AutoRegressive
    from: deeb.pipelines
    parameters: 
      order: 6
    
  - name: PowerSpectralDensity
    from: deeb.pipelines
      
  - name: RandomForestClassifier
    from: sklearn.ensemble
    parameters: 
        class_weight: "balanced"

  
  




