name: "UserDataset"

dataset: 
  - name: ERPCOREN400
    from: datasets
    parameters: 
      subjects: 10
      interval: [-0.1, 0.9]
      rejection_threshold: 200


pipelines:

  # "AR+PSD+SVM": 
  #   - name: AutoRegressive
  #     from: brainModels.pipelines
  #     parameters: 
  #       order: 6
        
  #   - name: PowerSpectralDensity
  #     from: brainModels.pipelines
        
  #   - name: SVC
  #     from: sklearn.svm
  #     parameters: 
  #       kernel: 'rbf'
  #       class_weight: "balanced"
  #       probability: True

  "Siamese": 
    - name : Siamese
      from: featureExtraction
      parameters: 
        #user_siamese_path: "configuration_files/siamese.yml"
        EPOCHS: 10
        batch_size: 256
        verbose: 1
        workers: 1

  
  "AR+PSD+RF": 
  - name: AutoRegressive
    from: featureExtraction
    parameters: 
      order: 6
    
  - name: PowerSpectralDensity
    from: featureExtraction
      
  - name: RandomForestClassifier
    from: sklearn.ensemble
    parameters: 
        class_weight: "balanced"

  
  




