name: "UserDataset"

dataset: 
  - name: ERPCOREN400
    from: brainModels.datasets
    parameters: 
      subjects: 10
      interval: [-0.1, 0.9]
      rejection_threshold: 200


pipelines:

  "AR+PSD+SVM": 
    - name: AutoRegressive
      from: brainModels.featureExtraction
      parameters: 
        order: 6
        
    - name: PowerSpectralDensity
      from: brainModels.featureExtraction
        
    - name: SVC
      from: sklearn.svm
      parameters: 
        kernel: 'rbf'
        class_weight: "balanced"
        probability: True


  # "TNN": 
  # - name : TwinNeuralNetwork
  #   from: brainModels.featureExtraction
  #   parameters: 
  #     #user_siamese_path: "configuration_files/siamese.yml"
  #     EPOCHS: 10
  #     batch_size: 256
  #     verbose: 1
  #     workers: 1

  
  "AR+PSD+KNN": 
  - name: AutoRegressive
    from: brainModels.featureExtraction
    parameters: 
      order: 6
    
  - name: PowerSpectralDensity
    from: brainModels.featureExtraction
      
  - name: KNeighborsClassifier
    from: sklearn.neighbors
    # parameters: 
    #     class_weight: "balanced"

    
 

  
  




